doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'
    enable_profiler: '%kernel.debug%'
    transactional: true
    check_database_platform: true