parameters:
    locale: en
    env(DATABASE_URL): 'mysql://root:@mysql:3306/symfony?serverVersion=5.7&charset=utf8mb4'
    env(DATABASE_USER): 'root'
    env(DATABASE_PASSWORD): ~
    env(SECRET): 'secret'
    
framework:
    secret: '%env(SECRET)%'
    router:
        strict_requirements: ~
        utf8: true
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    messenger:
        reset_on_message: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

webpack_encore:
    output_path: '%kernel.project_dir%/web/build'

