apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-php
  labels:
    app: deployment-php
spec:
  selector:
    matchLabels:
      app: deployment-php
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: deployment-php
      annotations:
        forceRoll: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: deployment-php
          image: "{{ .Values.dockerRegistryPrefix }}fbpviewer_prod_php"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 9000
          env:
            {{ if .Values.doctrine.walletSso }}
            - name: ORACLE_CWALLET_SSO
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: wallet_sso
            {{ end }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: url
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: APP_ENV
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: deployment-php
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    app: deployment-nginx
spec:
  selector:
    matchLabels:
      app: deployment-nginx
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: deployment-nginx
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: deployment-nginx
          image: "{{ .Values.dockerRegistryPrefix }}fbpviewer_prod_nginx"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: NGINX_HOST
              value: {{ .Values.nginxHost }}
            - name: NGINX_PORT
              value: "8080"

---
kind: Service
apiVersion: v1
metadata:
  name: lb
  labels:
    app: lb
  annotations:
{{ toYaml .Values.serviceAnnotations | indent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: deployment-nginx
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: 8080
{{ if .Values.publicIp }}
  loadBalancerIP: {{ .Values.publicIp }}
{{ end }}