apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
stringData:
  url: {{ .Values.doctrine.url | quote }}
  user: {{ .Values.doctrine.user | quote }}
  databaseName: {{ .Values.mysql.auth.database | quote }}
  password: {{ .Values.doctrine.password | quote }}
  rootPassword: {{ .Values.mysql.auth.rootPassword | quote }}
  {{ if .Values.doctrine.walletSso }}
  wallet_sso: {{ .Values.doctrine.walletSso | quote }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  endpointUrl: {{ .Values.s3_backups.endpointUrl }}
  accessKeyId: {{ .Values.s3_backups.accessKeyId }}
  secretAccessKey: {{ .Values.s3_backups.secretAccessKey }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
