apiVersion: v1
kind: Secret
metadata:
  name: oracle-db
type: Opaque
stringData:
  url: {{ .Values.doctrine.url | quote }}
  user: {{ .Values.doctrine.user | quote }}
  password: {{ .Values.doctrine.password | quote }}
  wallet_sso: {{ .Values.doctrine.walletSso | quote }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: ocirsecret
type: kubernetes.io/dockerconfigjson
