parameters:

services:
    AppBundle\Controller\:
        autoconfigure: true
        autowire: true
        resource: '%kernel.project_dir%/src/AppBundle/Controller/*'
        tags: [ 'controller.service_arguments' ]

    AppBundle\Repository\SharedBlueprintRepository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\SharedBlueprint

    AppBundle\Manager\SharedBlueprintManager:
        class: AppBundle\Manager\SharedBlueprintManager
        arguments: ['@AppBundle\Repository\SharedBlueprintRepository', '@Symfony\Component\HttpFoundation\RequestStack']